version: '3.8'
services:
  db:
    container_name: PgServer
    image: 'postgis/postgis:latest'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
  pgadmin:
    container_name: PgAdmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
  test-db:
    container_name: TestPgServer
    image: 'postgis/postgis:latest'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
